apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment

data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  # these lables are deployment lables
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment
    spec:
      containers:
      - name: payment
        image: vinod1618/payment:1.6.0
        imagePullPolicy: Always  # this is safe to pull evrytime, there may be images with same version rebuilt and pushes
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "150Mi"
        #readiness probe

        readinessProbe:
          httpGet:
              path: /health
              port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        #liveness probe

        livenessProbe:
          tcpSocket:
              port: 8080
          failureThreshold: 2
          periodSeconds: 10

        envFrom:
        - configMapRef:
            name: payment

---

apiVersion: v1
kind: Service
metadata: 
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  selector:
  #lables are used as selectors
    project: roboshop
    tier: backend
    component: payment
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port