apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these lables are replica set lables
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod
    matchLabels:
    project: roboshop
    tier: database
    component: mongodb
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: vinod1618/mongodb:1.0.0

---

apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  selector:
  #lables are used as selectors
    project: roboshop
    tier: database
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port